language: node_js
node_js:
  - lts/*

services:
  - docker

# safelist
branches:
  only:
  - master

script:
- node -v
- cd magnet2torrent
- CI=true docker-compose up --exit-code-from webtorrent --abort-on-container-exit
- cat torrents/7FA6EC9C323CA54A33DF16C8F41272A41A8ACB32.torrent.meta.json
